# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W9n55sLOSObF0w9ikMgLNleOg9NgsVow
"""

!pip uninstall -y langchain langchain-core langchain-community langchain-google-genai
!pip install langchain==0.1.20 langchain-google-genai==0.0.6

import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyDhgTbGLFzrAuM0pU1OAcgNDAFq2BIubyw"

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.agents import initialize_agent, AgentType
from langchain.tools import Tool

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.7
)

def generate_questions(role):
    return llm.invoke(f"""
    Generate 3 interview questions for {role} role.
    Make them beginner, intermediate, advanced.
    """).content

def evaluate_answer(answer):
    return llm.invoke(f"""
    Evaluate this answer:

    {answer}

    Give output in this format:
    Score: x/10
    Feedback:
    Improvement:
    """).content

def hr_question(_):
    return llm.invoke("Ask one HR interview question for a job interview").content

tools = [
    Tool(
        name="Question Generator",
        func=generate_questions,
        description="Generates interview questions based on role"
    ),
    Tool(
        name="Answer Evaluator",
        func=evaluate_answer,
        description="Evaluates answers and gives feedback"
    ),
    Tool(
        name="HR Question",
        func=hr_question,
        description="Generates HR questions"
    )
]

agent = initialize_agent(
    tools,
    llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True
)

print("🎯 AI Interview Simulator Started\n")

role = input("Enter role (Frontend / Java / Data Science): ")

# Step 1: Questions
questions = generate_questions(role)
print("\n📌 Questions:\n", questions)

# Step 2: Answer + Evaluation
answers = []

for i in range(3):
    ans = input(f"\nYour Answer {i+1}: ")
    answers.append(ans)

    result = evaluate_answer(ans)
    print("\n📊 Evaluation:\n", result)

# Step 3: Weak Area Analysis ⭐
combined_answers = " ".join(answers)

weak = llm.invoke(f"""
Analyze these answers:

{combined_answers}

Tell weak areas of the candidate.
""").content

print("\n📉 Weak Areas:\n", weak)

# Step 4: HR Round
print("\n--- 💼 HR ROUND ---")

hr_q = hr_question("")
print("\nHR Question:", hr_q)

hr_ans = input("\nYour HR Answer: ")

hr_eval = evaluate_answer(hr_ans)
print("\n📊 HR Evaluation:\n", hr_eval)